host: localhost
port: 8000

polling_interval: 5

sentinel_peers:
  - host: "localhost"
    port: 8001
  
  - host: "localhost"
    port: 8002

app_instances:
  - host: "localhost"
    port: 9001

  - host: "localhost"
    port: 9003
